#include<stdio.h>
#include<Windows.h>

void gotoXY(int, int);

void badEndingDraw() {
	int tme = 0;
	int num = 0;
	while (1) {
		if (num == 0) {
			system("cls");
			printf("\n\n\n\n\n");
			printf("					■■■■■■■■■■■■■■■■■■■■\n");
			printf("					■                                    ■\n");
			printf("					■        ■■■      ■■■  ■  ■  ■\n");
			printf("					■        ■  ■  ■      ■  ■  ■  ■\n");
			printf("					■        ■■■      ■■■  ■■■  ■\n");
			printf("					■        ■  ■  ■      ■      ■  ■\n");
			printf("					■        ■■■      ■■■      ■  ■\n");
			printf("					■                                    ■\n");
			printf("					■■■■■■■■■■■■■■■■■■■■\n");
			num = 1;
		}
		else if (num == 1) {
			system("cls");
			printf("\n\n\n\n\n");
			printf("					■■■■■■■■■■■■■■■■■■■■\n");
			printf("					■                                    ■\n");
			printf("					■        ■■■      ■■■  ■  ■  ■\n");
			printf("					■        ■  ■          ■  ■  ■  ■\n");
			printf("					■        ■■■      ■■■  ■■■  ■\n");
			printf("					■        ■  ■          ■      ■  ■\n");
			printf("					■        ■■■      ■■■      ■  ■\n");
			printf("					■                                    ■\n");
			printf("					■■■■■■■■■■■■■■■■■■■■\n");
			num = 0;
		}
		Sleep(500);
		tme++;
		if (tme == 6) {
			break;
		}
	}

	system("cls");

	gotoXY(50, 50);
	printf("\n\n\n\n\n\n\n                                                              어");
	Sleep(30);
	gotoXY(52, 50);
	printf("?");
	Sleep(30);
	gotoXY(52, 50);
	printf("라");
	Sleep(30);
	gotoXY(56, 50);
	printf("늦");
	Sleep(30);
	gotoXY(58, 50);
	printf("었");
	Sleep(30);
	gotoXY(60, 50);
	printf("다");
	Sleep(30);
	gotoXY(61, 50);
	printf(".");
	Sleep(30);
	gotoXY(62, 50);
	printf(".");
	Sleep(30);
	gotoXY(63, 50);
	printf(".");
	Sleep(30);
	gotoXY(65, 50);
	printf("또");
	Sleep(30);
	gotoXY(69, 50);
	printf("깨");
	Sleep(30);
	gotoXY(71, 50);
	printf("지");
	Sleep(30);
	gotoXY(73, 50);
	printf("갰");
	Sleep(30);
	gotoXY(75, 50);
	printf("네");
	Sleep(30);
	gotoXY(77, 50);
	printf(".");
	Sleep(30);
	gotoXY(78, 50);
	printf(".");
	Sleep(30);
	gotoXY(79, 50);
	printf(".");
	Sleep(2000);

	system("cls");

	printf("\n");
	printf("\n");
	printf("            sQBBDgBB5                          \n");
	printf("          sBZ:       BBBBB\B                         \n");
	printf("         SB                Br                        \n");
	printf("         Q   현우야.        RB                        \n");
	printf("         B;  맞아야겠지?   ,B                         \n");
	printf("         .Br         ,,:;BB                          \n");
	printf("           BBOZBBg  B                          \n");
	printf("                 gB B                          \n");
	printf("                  .p,                          \n");
	printf("\n");
	printf("                    _─────────── __\n");
	printf("                _ ─                ─ _\n");
	printf("              /               _____   ＼\n");
	printf("             /      ________-       ＼  ＼\n");
	printf("           /    _-                   ＼  ＼\n");
	printf("          │    /  _==-_               ＼  ＼\n");
	printf("          │   │  ________     _-===_  ＼  │\n");
	printf("          │   │ │        │__┌─────── _  │  │\n");
	printf("          │   │ │________/  │        │==│  │\n");
	printf("           ＼ │         │   I＼______/  │  │\n");
	printf("            │ │         /    ＼         │__/ \n");
	printf("             ＼│       (∩__ ∩)        │ │\n");
	printf("               │      /         ＼      │_/\n");
	printf("               │        _===_==_       / \n");
	printf("                ＼     ＼______/      /\n");
	printf("                │ ＼                 /\n");
	printf("              _-│   ＼              /\n");
	printf("          _─ ＼ │      ─-________ -\n");
	printf("    __──       ＼                 │-__\n");
	printf("───              ＼               /    ──  ____\n");
	printf("        ┌───────┐  -___          /             ＼\n");
	printf("        │ 사감쌤│        ──────                  ＼\n");
	printf("        └───────┘  \n");


	Sleep(4000);

	system("cls");

	printf("\n\n\n\n\n\n                          ~@@;  \n");
	printf("           ...      @@    ~@#@;   \n");
	printf("          ;@@@:,    @@    ~* :#;\n");
	printf("          ;@$=@@,  ~#=,   ~*  ;@~\n");
	printf("          ;$:-$=.  @- #   ~=, ~#:\n");
	printf("          ;@@@@,   @~:#:;-~@!  !;\n");
	printf("          ;@=!#!. :@@@*@!:~@! ,=~ \n");
	printf("          ;@~ ~#, @;;;.$  ~@!-=$-\n");
	printf("          ;@=!!#, @   .@: ~@$$$~\n");
	printf("          ;@@@!~  ~   .@$ .!@=- \n");
	printf("          ,---.        :$  .-, \n");
	printf("                        , \n");
	printf("\n");
	printf("      .                     \n");
	printf(",,,,,:@;          ,,,        \n");
	printf("@@@@@@*   ..  ,-  @@@,    .  .-.  ,    -   \n");
	printf("@@@@=*:   ;!. =@, @==@-  -!  ;@: -#,  -@-- \n");
	printf("*@@$      ;@!.=@, @  *#- -*  ;@*.:#,  @**! \n");
	printf(" @@#:~    ;@#-=@, @   @$ -$- ;$$~ =, ~@    \n");
	printf(";@@@@=    ;=$;$@, @;  ;#,-@* ;;!*,=, #;    \n");
	printf(":@@::~    ;:*$@@, @@  .#,-@* ;;-$;$, # !!!!\n");
	printf(" !#       ;:-$@@, @@  *$ -@* ;; *#@, #*~~@@; \n");
	printf(" .#   ,=: ;: *@@, @@ =@~ .;* ;; ,$@, #@  @@$\n");
	printf("  @===$@!.!: ,$@, @@$@-   ~* ;;  *@, ,@$$@@$\n");
	printf("  @@@$,,. !:  =@, ,@@,    ~* ;;  .$,  ,@@-@$ \n");
	printf("  @@@$,,. !:  =@, ,@@,    ~* ;;  .$,  ,@@-@$ \n");

	printf("돌아가려면 스페이스바를 눌러주십시오.");
	while (1) {
		if (Getkeydown(VK_SPACE))
			break;
	}
}

void happyEndingDraw() {
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("                                          .;!!!!!!;,\n");
	printf("              :                      ;;*:::~,....,~:::-*;;\n");
	printf("              ,, ,                :*;...........,,,..,   :\n");
	printf("               ~~,              ~!-....,!!*~~~~~~~~~~~~~!*\n");
	printf("         .   - .              -;~...,;;:.       ,~~~~~~~.                                -!*,\n");
	printf("          !  * .-==--        -*...-;!---~=!!!!!!!!!:::=$$$$$$$$$=~--------             -**:;:\n");
	printf("         ,, * -=**! !!~,.  .*....***................,;;;;;;;;;;;;;;;;;;!$$$$$$$$$=~,,*!:;*-  \n");
	printf("            != ;****..  ,*!!=........................,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;*\n");
	printf("              =******   :    -.......................,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*;;*\n");
	printf("              !****  *,-=:   =.......................,;;;$                              \n");
	printf("            = !**** =   :    ,.......................,;;;*===========================$**!\n");
	printf("        -- !   =**; ..  .=**=........................,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;* \n");
	printf("        : .!  !.=*.  !!~..  ,*....***................,;;;;;;;;;;;;;;;;;;;*$$$$$$$$$*-,*;:;*-\n");
	printf("       .   ;  ; ~=!-,        ,*...,=*,,,:=*******!~---*$$$$$$$$$$*~,,,,,,,,            ,**:;~\n");
	printf("           ,   :   :          ,*....:!;-       .--------,                                ,!*, \n");
	printf("               !    =           !!.....:;*::::~,  .-:::::!\n");
	printf("              ~.-   !            ,:!;........,;!!!!;-,   :\n");
	printf("              ,      ~              -:*;;:-........,:;~~!:\n");
	printf("              ,      ;                   ,;;;;;;;;;;: \n");
	printf("              .\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("                       .;!!!!!!;,\n");
	printf("              :       ::~,....,~:::-*;;\n");
	printf("              ,, ,    .......,,,..,   :\n");
	printf("               ~~,    !*~~~~~~~~~~~~~!*\n");
	printf("         .   - .             ,~~~~~~~.                                -!*,\n");
	printf("          !  * .-==-- =!!!!!!!!!:::=$$$$$$$$$=~--------             -**:;:\n");
	printf("         ,, * -=**! !!...........,;;;;;;;;;;;;;;;;;;!$$$$$$$$$=~,,*!:;*-  \n");
	printf("            != ;****..............,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;*\n");
	printf("              =****** ............,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*;;*\n");
	printf("              !****  *............,;;;$                              \n");
	printf("            = !**** = ............,;;;*===========================$**!\n");
	printf("        -- !   =**; ..............,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;* \n");
	printf("        : .!  !.=*.  !............,;;;;;;;;;;;;;;;;;;;*$$$$$$$$$*-,*;:;*-\n");
	printf("       .   ;  ; ~=!-, =*******!~---*$$$$$$$$$$*~,,,,,,,,            ,**:;~\n");
	printf("           ,   :   :        .--------,                                ,!*, \n");
	printf("               !    = *::::~,  .-:::::!\n");
	printf("              ~.-   ! ....,;!!!!;-,   :\n");
	printf("              ,      ~:-........,:;~~!:\n");
	printf("              ,      ;,;;;;;;;;;;: \n");
	printf("              .\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("                     \n");
	printf("              :      ::-*;;\n");
	printf("              ,, ,   .,   :\n");
	printf("               ~~,   ~~~~!*\n");
	printf("         .   - .     ~~~~.                                -!*,\n");
	printf("          !  * .-==--::=$$$$$$$$$=~--------             -**:;:\n");
	printf("         ,, * -=**! !,;;;;;;;;;;;;;;;;;;!$$$$$$$$$=~,,*!:;*-  \n");
	printf("            != ;****..,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;*\n");
	printf("              =******.,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*;;*\n");
	printf("              !****  .,;;;$                              \n");
	printf("            = !**** =.,;;;*===========================$**!\n");
	printf("        -- !   =**; ..,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!::;* \n");
	printf("        : .!  !.=*.  .,;;;;;;;;;;;;;;;;;;;*$$$$$$$$$*-,*;:;*-\n");
	printf("       .   ;  ; ~=!-,--*$$$$$$$$$$*~,,,,,,,,            ,**:;~\n");
	printf("           ,   :   : ----,                                ,!*, \n");
	printf("               !    =:::::!\n");
	printf("              ~.-   !-,   :\n");
	printf("              ,      :;~~!:\n");
	printf("              ,      : \n");
	printf("              .\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("                     \n");
	printf("              :      ::-*;;\n");
	printf("              ,, ,   .,   :\n");
	printf("               ~~,   ~~~~!*\n");
	printf("         .   - .     ~~~~.-!*,\n");
	printf("          !  * .-==--::-             -**:;:\n");
	printf("         ,, * -=**! !,;$$$$$$$$=~,,*!:;*-  \n");
	printf("            != ;****..,;;;;;;;;;;;;!::;*\n");
	printf("              =******.,;;;;;;;;;;;;*;;*\n");
	printf("              !****  .,               \n");
	printf("            = !**** =.,============$**!\n");
	printf("        -- !   =**; ..,;;;;;;;;;;;;!::;* \n");
	printf("        : .!  !.=*.  .,*$$$$$$$$$*-,*;:;*-\n");
	printf("       .   ;  ; ~=!-,--,,            ,**:;~\n");
	printf("           ,   :   : ----, ,!*, \n");
	printf("               !    =:::::!\n");
	printf("              ~.-   !-,   :\n");
	printf("              ,      :;~~!:\n");
	printf("              ,      : \n");
	printf("              .\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("                     \n");
	printf("              :      ::-*;;\n");
	printf("              ,, ,   .,   :\n");
	printf("               ~~,   ~~~~!*\n");
	printf("         .   - .     ~~~~.-!*,\n");
	printf("          !  * .-==--::-  -**:;:\n");
	printf("         ,, * -=**! !,;$*!:;*-  \n");
	printf("            != ;****..,;!::;*\n");
	printf("              =******.,;*;;*\n");
	printf("              !****  .,    \n");
	printf("            = !**** =.,=$**!\n");
	printf("        -- !   =**; ..,;!::;* \n");
	printf("        : .!  !.=*.  .,*,*;:;*-\n");
	printf("       .   ;  ; ~=!-,--,,  ,**:;~\n");
	printf("           ,   :   : ----,,!*, \n");
	printf("               !    =:::::!\n");
	printf("              ~.-   !-,   :\n");
	printf("              ,      :;~~!:\n");
	printf("              ,      : \n");
	printf("              .\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("               \n");
	printf("         -    \n");
	printf("           ~  .  \n");
	printf("           :   \n");
	printf("           :   \n");
	printf("           -,~  \n");
	printf("           -~~  \n");
	printf("            ~-  \n");
	printf("          :~:~\n");
	printf("           ~:~~   \n");
	printf("           ;;:-  \n");
	printf("          ,:!;~- \n");
	printf("           ;!;:   \n");
	printf("        -  !*!- \n");
	printf("        -  **!;  \n");
	printf("        ! ;;=!;.  \n");
	printf("        .-===*;     \n");
	printf("        ;!.=:*;     \n");
	printf("        ;* *!*;  \n");
	printf("        ;*  =,-.\n");
	printf("        ;*   -.. \n");
	printf("       .;*  =!\n");
	printf("       ,;-. =\n");
	printf("       -; = =  \n");
	printf("       -: =. \n");
	printf("       ~: *=*;\n");
	printf("          **~- \n");
	printf("          !*! \n");
	printf("         ,!!!~\n");
	printf("         :;!!: \n");
	printf("         :;;:: \n");
	printf("         ~::::  \n");
	printf("         .~:~ \n");
	printf("        , ~~,\n");
	printf("         .~--\n");
	printf("         ,---\n");
	printf("          -.~\n");
	printf("          - ~ \n");
	printf("          ~ ~ \n");
	printf("          ,\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(500);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(" @@  ,@$                                           \n");
	printf(" @@  ,@$ \n");
	printf(" @@  ,@$ \n");
	printf(" @@..-@$  -##@*.  !:!#@-  $,=#@.  @$ .@$  \n");
	printf(" @@###@$    .:#;  !:  *-  $,  #!  @$ .@$  \n");
	printf(" @@  ,@$   :@$#;  !:  *-  $,  #!  @$ .@$ \n");
	printf(" @@  ,@$  :@;~#;  !:  *-  $,  #!  @$ .@$ \n");
	printf(" @@  ,@$ -@* ~#;  !:  *-  $,  #!  @$ .@$	\n");
	printf(" @@  ,@$ -@=-;@;  !:,-=-  $, ,@;  @$-~@$\n");
	printf(" @@  ,@$ ,$@@@@;  !!=@$,  $,-#$,  =@@=@$ \n");
	printf(" **  .*;  ,****~  !$**,   $,!*-    **.@$  \n");
	printf("                  !:      $,         .@$\n");
	printf("                  !:      $,         .@$\n");
	printf("                  !:      $,      :::;@;\n");
	printf("                  ~-      :.      !!!!; \n");
	printf("\n");
	printf("                   -,              \n");
	printf("!!!!!;             !~  :!.               \n");
	printf(":;:::~             !:  -:.              \n");
	printf(",*                 !:                     \n");
	printf("=@     .;,**:  -**-!:   ;, !****    ****; \n");
	printf("@@ **! ,=.~!*  :*~.!:  ;#- $@:~@=  =@~~~- \n");
	printf("@@=@@$ ,=  ~*  ;;  !:  =@- $@. @@  @#    \n");
	printf("@@---, ,=  ~*  ;;  !:  =@- $@. @@  @# .=!\n");
	printf("@@     ,=  ~*  ;;  !:  =@- $@. @@  @# ,@$  \n");
	printf("@@     ,=  ~*  ;;  !:  =@- $@. @@  @# ,@$ \n");
	printf("@@     ,=  ~*  ;;  !:  =@- $@. @@  @# ,@$ \n");
	printf("@@###= ,=  ~*   ;#:!:  =@- $@. @@  ,@=,@$\n");
	printf("......  .        .      .  ..  ..   ..,@$\n");
	printf("                                      ,@$\n");
	printf("                                      ,@$\n");
	printf("                                   .@@@$  \n");

	printf("돌아가려면 스페이스바를 눌러주십시오.");
	while (1) {
		if (Getkeydown(VK_SPACE))
			break;
	}
}

void trueEndingDraw() {
	printf("\n");
	printf("\n");
	printf("\n");
	printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	printf("                     ＼         │                                                   __─ \n");
	printf("                      ＼        │                                               __─  \n");
	printf("                       ＼       │                                           __─   \n");
	printf("                        ＼      │                                       __─   \n");
	printf("                         ＼_____│                                   __─   \n");
	printf("                                                                __─    \n");
	printf("───────────────────────────────────────────────────────────────┐\n");
	printf("                                                               │\n");
	printf("            ┌────────────────┬────────────────┐          ______│_____\n");
	printf("            │┌───────────────│┌──────────────┐│        /│           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││               ││              ││       │ │           │\n");
	printf("            ││─┬──┬──┬──┬──┬─││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │ │           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │─┤           │\n");
	printf("            ││ │  │  │  │  │ ││              ││       │-│          _│___\n");
	printf("            ││─┴──┴──┴──┴──┴─││              ││_______│_│_________€       ＼\n");
	printf("            ││───────────────││              │＼        ＼         ＼        ＼\n");
	printf("____________││_______________││______________│ ＼        ＼          ＼        ＼\n");
	printf("                                             │  ＼        ＼  _______────────────────────\n");
	printf("                                             │＼ ＼          │                           \n");
	printf("                                             │ ＼  ＼       _│\n");
	printf("                                             ＼ ＼  ＼     ├─│                  __________\n");
	printf("                                              ＼ ＼   ＼   │ │            __───\n");
	printf("                                               ＼ │＼  ＼  │ │           ─\n");
	printf("                                                ＼│ ＼  ＼ │_│__________＼\n");
	printf("                                                 ＼  ＼  ＼ ─             ＼\n");
	printf("                                                  ＼  ＼  │  ＼              ＼\n");
	printf("                                                   ＼  ＼ │   ＼              ＼\n");
	printf("                                                    ＼  ＼│    ＼               ＼________\n");
	printf("                                                     ＼   │     ＼\n");
	printf("                                                      ＼  │       ＼\n");
	printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(1000);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	printf("  ─── ___                                                                                                                                             ___ ───\n");
	printf("          ─── ___                                                                                                                             ___ ───\n");
	printf("                  ─── ___                                                                                                             ___ ───\n");
	printf("                          ─── ___                                                                                             ___ ───\n");
	printf("                                  ─── ___                                                                             ___ ───\n");
	printf("                                          ─── ___                                                             ___ ─── '\n");
	printf("                                                  ─── ___                                             ___ ───\n");
	printf("                                 ┌──────────┐-_           ─── ___                             ___ ───\n");
	printf("                                 │          │   -_                ─── ___________________ ───\n");
	printf("                                 │          │      -_\n");
	printf("                                 │          │        │\n");
	printf("                                 │          │        │      ┌────┐_      ┌──────────┐         ┌─────┐\n");
	printf("                                 │          │        │      │    │ │     │          │        /│     │\n");
	printf("                                 │          │        │      │    │ │     │          │       │ │     │\n");
	printf("                                 │          │        │      │    │ │     │          │       │ │     │\n");
	printf("                                 │          │        │      │    │ │     │        ∂│       │ │     │\n");
	printf("                                 │          │        │      │    │ │     │          │       │ │     │\n");
	printf("                                 │          │        │______│____│_│     │          │  _____│ │_____│_\n");
	printf("                                 │          │       |│           _-│     │          │ │ -_             -_  \n");
	printf("                                 │          │       |│        _-   │     │__________│ │    -_     _________________________________\n");
	printf("                                 │          │        │     _-      │    /            ＼-_    -_ │                                  │\n");
	printf("                                 │          │        │  _-         │   /_______________＼-_    -│                                  │\n");
	printf("                        ___ ───────────────────────────────      _-                        -_   ├──────────────────────────────────┘__                               \n");
	printf("                  __ ──                                   _-│  _-                            -_ │ -_                                   ── __                                        \n");
	printf("            __ ──                                      _-   │_-                                -│   -_                                       ── __                                       \n");
	printf("      __ ──                                         _-      │                                   │      -_                                          ── __                                \n");
	printf("__ ──                                            _-         │                                   │         -_                                             ── _                          \n");
	printf("                                              _-            │                                   │            -_                                                                     \n");
	printf("                                           _-               │                                   │               -_                                                                  \n");
	printf("                                        _-                _-                                     -_                -_                                                                \n");
	printf("                                     _-                 _-                                         -_                 -_                                                              \n");
	printf("                                  _-                  _-                                             -_                  -_                                                           \n");
	printf("                               _-                   _-                                                 -_                   -_                                                       \n");
	printf("                            _-                    _-                                                     -_                    -_                                                    \n");
	printf("                                                                                                                                                                          \n");
	printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");

	Sleep(1000);

	printf("\n\n\t\t\t\t\t\t\t\"지");
	Sleep(30);
	printf("옥");
	Sleep(30);
	printf("으");
	Sleep(30);
	printf("로");
	Sleep(30);
	printf(" ");
	Sleep(30);
	printf("복");
	Sleep(30);
	printf("귀\"");

	Sleep(3000);
	system("cls");

	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("          =,                          \n");
	printf("         .$~,.  . -- ..   .,   ,-~,.  \n");
	printf("         ;@==! .#:=: ;;   #@  .@==$*.\n");
	printf("          =,   .@:   ;;   #@  ;$  :@:\n");
	printf("          =,   .#    ;;   #@  @#;;=@:  \n");
	printf("          =,   .#    ;;   #@  @#~~~~,  \n");
	printf("          =,   .#    ;;   #@  @$       \n");
	printf("          =$.  .#    ;@~ =@@  -@*      \n");
	printf("          =@@, .#    :@@@:#@   ,@@@@:\n");
	printf("\n");
	printf("       8               ,.                          \n");
	printf(":::::-                !~  ~:\n");
	printf("@@;;;-                !~  #@ \n");
	printf("@#                    !~  -~  \n");
	printf("@#      :-!==.    ~==~!~  *=  .! -==~    ===.* \n");
	printf("@#      !@@-##   :*..;@~  #@  .#**;@:   =@.,#$ \n");
	printf("@@@@@*  !@-  @  ,@=   !~  #@  .@=  ;@~ =@.  .$	\n");
	printf("@#      !~   @  ,$    !~  #@  .$   ;@~ =*   .$\n");
	printf("@#      !~   @  ,$    !~  #@  .$   ;@~ =~   .$\n");
	printf("@#      !~   @  ,#-  ,=~  #@  .$   ;@~ =@.  :$ \n");
	printf("@@~~~~, !~   @  ,@$-,;$~  #@  .$   ;@~ :@;;;!$  \n");
	printf("@@####; !~   @   !@#;,!~  #@  .$   ;@~  ~:;:.$  \n");
	printf("------, ,.   -    --, ,.  --   -   .-.      .$  \n");
	printf("                                        ,   #$  \n");
	printf("                                        $@@@#   \n");
	printf("\n");
	printf("\n");
	printf("\n");

	printf("\n\n\n\t\t\t\t돌아가려면 스페이스바를 눌러주십시오.");
	while (1) {
		if (Getkeydown(VK_SPACE))
			break;
	}
}